### ISSUE TITLE
Segmentation Fault when running the ur5 example

### ISSUE THREAD

**Issue by tannerliu347** [stack-of-tasks/pinocchio-gepetto-viewer#1]
Hi, I was able to install the library but when I tried running the ur5 example, it compiles fine but runs with a Segmentation fault error.  When trying to debug in CLion it doesn't stop on a breakpoint on the first line of main but goes into assembly code directly. Any insight? Thanks.

**Comment by jmirabel** [comment]
The segfault thus happens when loading some libraries. I guess the dependencies found at runtime are not the same as the one found at compile time.

Check your environment variable. Use `ldd` to check what is found at runtime.

**Comment by tannerliu347** [comment]
Thanks for the hint. I was able to resolve this issue. Now I'm getting a error: "File: /opt/openrobots/share/example-robot-data/robots/ur_description/meshes/ur5/visual/base.dae could not be loaded". So I tried installing robotpkg-osg-dae, but it has a broken dependencies on robotpkg-collada-dom. Error message: "robotpkg-osg-dae : Depends: robotpkg-collada-dom (= 2.3.1r2) but 2.4.0r1 is to be installed".

**Comment by jmirabel** [comment]
I let @nim65s answer to this. There has been recent changes on the DAE plugin on robotpkg and you do not have to install `robotpkg-osg-dae` anymore. Everything should be installed with `robotpkg-py??-qt?-gepetto-viewer-corba`.

**Comment by tannerliu347** [comment]
Got it. So I built gepetto-viewer and gepetto-viewer-corba from source since you mentioned that this pinocchio-gepetto-viewer depends on devel branch of gepetto-viewer. So I can actually use the binary version of gepetto-viewer-corba from robotpkg?

**Comment by jmirabel** [comment]
> So I built gepetto-viewer and gepetto-viewer-corba from source since you mentioned that this pinocchio-gepetto-viewer depends on devel branch of gepetto-viewer.

I forgot about that. I think it hasn't been released yet. No, you cannot use gepetto-viewer-corba binaries.

If you need to load DAE files for something else than the unit test, I suggest you to wait for @nim65s answer. Otherwise, replace `pin::VISUAL` by `pin::COLLISION` in the unit test file.

**Comment by tannerliu347** [comment]
Yeah I actually don't need the DAE files for later. I replaced the pin::VISUAL to pin::COLLISION and everything worked. Thank you so much!
